import Head from 'next/head'
import Navbar from '../components/Navbar';
import HomePage from './homePage';
import Services from './services';
import Contact from './contact';
import Footer from '../components/Footer';


const Home = () => {
  return (
    <div className=' bg-black ' >
			<Head>
				<title>Ganesh uthiravasagam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

      <Navbar />
      <HomePage />
      <Services />
      <Contact />
      <Footer />
      

    </div>
  )
}

export default Home;